server.port=8082
spring.application.name=Note Candidat
spring.datasource.url=jdbc:postgresql://localhost:5432/candidat
spring.datasource.username=postgres
spring.datasource.password=harena
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.thymeleaf.cache=false
spring.web.resources.static-locations=file:src/main/resources/static/,classpath:/static/
